from __future__ import annotations

import json
from pathlib import Path
from fastapi import APIRouter

from app.models.schemas import MetricsResponse


router = APIRouter(prefix="/api/metrics", tags=["metrics"])


@router.get("", response_model=MetricsResponse)
def get_metrics() -> dict:
    """
    Returns the evaluation metrics of the currently deployed ML models.
    Metrics are dynamically generated by scripts/generate_metrics.py
    and read from models/metrics.json.
    """
    metrics_path = Path(__file__).resolve().parents[2] / "models" / "metrics.json"
    if metrics_path.exists():
        with open(metrics_path, "r", encoding="utf-8") as f:
            return json.load(f)
    return {"tuning": {}}
